=== Coreyeast/wsassignment/web/WEB-INF/users.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.

<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.uts.edu.au/31284/wsd-diary"
    xmlns="http://www.uts.edu.au/31284/wsd-diary"
    elementFormDefault="qualified"> -->
    
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:simpleType name="email">
        <xs:restriction base="xs:string">
            <xs:pattern value="\w+([-+.^_]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="name">
        <xs:restriction base="xs:string">
        </xs:restriction>
    </xs:simpleType>
    

    
    <xs:element name="users">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="user" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="email" type="email"/>
                            <xs:element name="name" type="name"/>
                            <xs:element name="password" type="xs:string"/>
                            <xs:element name="DOB" type="xs:date"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Coreyeast/wsassignment/web/WEB-INF/users.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

 <!--xmlns="http://www.uts.edu.au/31284/wsd-diary"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.uts.edu.au/31284/wsd-diary users.xsd"-->
 <users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="users.xsd">
    <user>
        <email>pplenge15@hotmail.com</email>
        <name>Patrick Plenge</name>
        <password>123</password>
        <DOB>12/01/1998</DOB>  
    </user>
    <user>
        <email>joe@bloggs.com</email>
        <name>Joe Bloggs</name>
        <password>foobar</password>
        <DOB>12/01/1998</DOB>  
    </user>
    <user>
        <email>coreyeast@gmail.com</email>
        <name>Corey East</name>
        <password>lmao</password>
        <DOB>12/01/1998</DOB>  
    </user>
    <user>
        <email>patt.stacked@gmail.com</email>
        <name>Potrick Plonk</name>
        <password>321</password>
        <DOB>12/01/1998</DOB>  
    </user>
</users>
